# Generated by Django 3.2.5 on 2022-08-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
